# values.yaml
namespace: aimevictorydarnel
replicaCount: 3

image:
  repository: aimevictory/mon-examen
  tag: latest

resources:
  limits:
    cpu: "1"
    memory: "100Mi"
  requests:
    cpu: "0.5"
    memory: "50Mi"

persistentVolumeClaim:
  storage: 1Gi

ingress:
  host: aimevictorydarnel-math.horizon-workspaces.com
  annotations:
    certManager: letsencrypt-prod
  tlsSecret: aimevictorydarnel-nginx-tls
service:
  type: ClusterIP
  ports:
    - name: http
      port: 8010
      targetPort: 8010



